name: Build, Scan & Deploy React App (No Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t docker-react-app:latest .

      - name: Save image as tar
        run: docker save docker-react-app:latest -o react-app.tar

      - name: Copy image to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: "react-app.tar"
          target: "~/"

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            docker load -i react-app.tar
            docker stop docker-react-app || true
            docker rm docker-react-app || true
            docker run -d -p 80:3000 --name docker-react-app docker-react-app:latest
